/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.tradetoday.graphics;

/**
 *
 * @author 18100527
 */
public class StockInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzePanel
     */
    public StockInfoPanel() {
        this.name = "DEFAULT_NAME";
        this.desc = "DEFAULT_DESC";
        generateLabels();
        initComponents();
    }
    
    StockInfoPanel(String[][] data,String[] header,String name,String desc){
        this.name = name;
        this.desc = desc;
        defineTableData(data,header);
        generateLabels();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicsPanel = new javax.swing.JPanel();
        infoScroll = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();
        lUpdtPanel = new javax.swing.JPanel();
        lstUpdtHead = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lUpdtScrll = new javax.swing.JScrollPane();
        lUpdtText = new javax.swing.JTextArea();
        lstUpdtHead1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lUpdtScrll1 = new javax.swing.JScrollPane();
        lUpdtText1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(42, 42, 42));
        setMaximumSize(new java.awt.Dimension(750, 540));
        setMinimumSize(new java.awt.Dimension(750, 540));
        setPreferredSize(new java.awt.Dimension(750, 540));

        graphicsPanel.setPreferredSize(new java.awt.Dimension(450, 300));

        javax.swing.GroupLayout graphicsPanelLayout = new javax.swing.GroupLayout(graphicsPanel);
        graphicsPanel.setLayout(graphicsPanelLayout);
        graphicsPanelLayout.setHorizontalGroup(
            graphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        graphicsPanelLayout.setVerticalGroup(
            graphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        infoScroll.setBackground(new java.awt.Color(30, 30, 30));
        infoScroll.setPreferredSize(new java.awt.Dimension(726, 200));

        infoTable.setBackground(new java.awt.Color(150, 150, 150));
        infoTable.setModel(new javax.swing.table.DefaultTableModel
            (tableData,tableHeader){
                @Override
                public boolean isCellEditable(int row, int column) {
                    //all cells false
                    return false;
                }
            });
            infoTable.setFillsViewportHeight(true);
            infoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            infoScroll.setViewportView(infoTable);
            /*CUSTOM CODE ZONE*/
            infoTable.getTableHeader().setReorderingAllowed(false);
            /*END OF CUSTOM CODE ZONE*/

            lUpdtPanel.setBackground(new java.awt.Color(70, 70, 70));

            lstUpdtHead.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
            lstUpdtHead.setForeground(new java.awt.Color(250, 250, 250));
            lstUpdtHead.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lstUpdtHead.setText("Last Update :");

            lUpdtScrll.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            lUpdtScrll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            lUpdtScrll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
            lUpdtScrll.setOpaque(false);

            lUpdtText.setEditable(false);
            lUpdtText.setBackground(new java.awt.Color(70, 70, 70));
            lUpdtText.setColumns(20);
            lUpdtText.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
            lUpdtText.setForeground(new java.awt.Color(250, 250, 250));
            lUpdtText.setRows(5);
            lUpdtText.setTabSize(4);
            lUpdtText.setText(generateLabels());
            lUpdtText.setHighlighter(null);
            lUpdtScrll.setViewportView(lUpdtText);

            javax.swing.GroupLayout lUpdtPanelLayout = new javax.swing.GroupLayout(lUpdtPanel);
            lUpdtPanel.setLayout(lUpdtPanelLayout);
            lUpdtPanelLayout.setHorizontalGroup(
                lUpdtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(lUpdtPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(lUpdtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lstUpdtHead, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(lUpdtScrll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            lUpdtPanelLayout.setVerticalGroup(
                lUpdtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lUpdtPanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(lstUpdtHead, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lUpdtScrll, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            lstUpdtHead1.setFont(new java.awt.Font("Ubuntu", 1, 28)); // NOI18N
            lstUpdtHead1.setForeground(new java.awt.Color(250, 250, 250));
            lstUpdtHead1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lstUpdtHead1.setText("Others Updates");

            jPanel1.setBackground(new java.awt.Color(70, 70, 70));

            jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
            jLabel1.setForeground(new java.awt.Color(250, 250, 250));
            jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel1.setText(name);

            lUpdtScrll1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
            lUpdtScrll1.setForeground(new java.awt.Color(250, 250, 250));
            lUpdtScrll1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
            lUpdtScrll1.setOpaque(false);

            lUpdtText1.setEditable(false);
            lUpdtText1.setBackground(new java.awt.Color(70, 70, 70));
            lUpdtText1.setColumns(20);
            lUpdtText1.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
            lUpdtText1.setForeground(new java.awt.Color(250, 250, 250));
            lUpdtText1.setLineWrap(true);
            lUpdtText1.setRows(5);
            lUpdtText1.setTabSize(4);
            lUpdtText1.setText(desc);
            lUpdtText1.setHighlighter(null);
            lUpdtScrll1.setViewportView(lUpdtText1);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lUpdtScrll1))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lUpdtScrll1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(graphicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lstUpdtHead1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lUpdtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addComponent(infoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(graphicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lUpdtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lstUpdtHead1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                    .addComponent(infoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
        }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphicsPanel;
    private javax.swing.JScrollPane infoScroll;
    private javax.swing.JTable infoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel lUpdtPanel;
    private javax.swing.JScrollPane lUpdtScrll;
    private javax.swing.JScrollPane lUpdtScrll1;
    private javax.swing.JTextArea lUpdtText;
    private javax.swing.JTextArea lUpdtText1;
    private javax.swing.JLabel lstUpdtHead;
    private javax.swing.JLabel lstUpdtHead1;
    // End of variables declaration//GEN-END:variables
    
    // Custom Variables
    private String[][] tableData = {{"24/07/2000","0.25","0.27","+0.01"},
                                    {"23/07/2000","0.25","0.25","+0.00"},
                                    {"22/07/2000","0.27","0.25","-0.01"}};
    private String[] tableHeader =  {"Date","Open","Close","Delta"};
    private String[]  lastUpdate = {"25/07/2000","0.27","0.29","+0.01"}; 
    private String labels = "";
    private String name;
    private String desc;
    
    private void defineTableData(String[][] data,String[] header){
        lastUpdate = data[0];
        tableHeader = header;
        for(int i = 1;i < header.length;i++){
            tableData[i-1] = data[i];
        }
    }
    
    private String generateLabels(){
        String r = "";
        for(int i = 0;i < tableHeader.length;i++){
            r += tableHeader[i] + " : " + tableData[0][i] + "\n";
        }
        return r;
    }
    
    public void update(String[][] data,String[] header,String name,String desc){
        this.name = name;
        this.desc = desc;
        defineTableData(data,header);
        generateLabels();
        initComponents();
        this.repaint();
    }
    
    public static void main(String[] args) {
        javax.swing.JFrame f = new javax.swing.JFrame();
        
        String[][] data = {         {"25/07/2000","0.27","0.29","+0.01"},
                                    {"24/07/2000","0.25","0.27","+0.01"},
                                    {"23/07/2000","0.25","0.25","+0.00"},
                                    {"22/07/2000","0.27","0.25","-0.01"}};
        String[] header =  {"Date","Open","Close","Delta"};
        
        StockInfoPanel s = new StockInfoPanel(data,header,"Microsoft Studios","My litte description");
        f.add(s);
        f.pack();
        f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
        
    }
    
}
