/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufsc.tradetoday.graphics;

/**
 *
 * @author 18100527
 */
public class StockInfoPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyzePanel
     */
    public StockInfoPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphicsPanel = new javax.swing.JPanel();
        infoScroll = new javax.swing.JScrollPane();
        infoTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(42, 42, 42));
        setMaximumSize(new java.awt.Dimension(750, 540));
        setMinimumSize(new java.awt.Dimension(750, 540));
        setPreferredSize(new java.awt.Dimension(750, 540));

        javax.swing.GroupLayout graphicsPanelLayout = new javax.swing.GroupLayout(graphicsPanel);
        graphicsPanel.setLayout(graphicsPanelLayout);
        graphicsPanelLayout.setHorizontalGroup(
            graphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        graphicsPanelLayout.setVerticalGroup(
            graphicsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        infoScroll.setBackground(new java.awt.Color(30, 30, 30));
        infoScroll.setPreferredSize(new java.awt.Dimension(726, 250));

        infoTable.setBackground(new java.awt.Color(150, 150, 150));
        infoTable.setModel(new javax.swing.table.DefaultTableModel
            (tableData,tableHeader){
                @Override
                public boolean isCellEditable(int row, int column) {
                    //all cells false
                    return false;
                }
            });
            infoTable.setFillsViewportHeight(true);
            infoTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
            infoScroll.setViewportView(infoTable);
            /*CUSTOM CODE ZONE*/
            infoTable.getTableHeader().setReorderingAllowed(false);
            /*END OF CUSTOM CODE ZONE*/

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
            this.setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(graphicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(infoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(graphicsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(infoScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
        }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphicsPanel;
    private javax.swing.JScrollPane infoScroll;
    private javax.swing.JTable infoTable;
    // End of variables declaration//GEN-END:variables
    
    // Custom Variables
    private String[][] tableData = {{"24/07/2000","0.25","0.27","+0.01"},
                                    {"23/07/2000","0.25","0.25","+0.00"},
                                    {"22/07/2000","0.27","0.25","-0.01"}};
    private String[] tableHeader =  {"Date","Open","Close","Delta"};
    
    
    public static void main(String[] args) {
        javax.swing.JFrame f = new javax.swing.JFrame();
        StockInfoPanel s = new StockInfoPanel();
        f.add(s);
        f.pack();
        f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        f.setVisible(true);
        
    }
}
